version: "3.7"
services:
  onedrive:
    image: driveone/onedrive:edge
    container_name: onedrive
    restart: unless-stopped
    environment:
     - ONEDRIVE_UID=${PUID}
     - ONEDRIVE_GID=${PGID}
    volumes:
      - ${APP_DATA_DIR}/onedrive_conf:/onedrive/conf
      - ${UMBREL_ROOT}/home/Documents/XXX:/onedrive/data
